SEED_CASES = [
    {
        "slug": "kesavananda-bharati-v-state-of-kerala-1973",
        "case_name": "Kesavananda Bharati Sripadagalvaru Keshava v. State of Kerala",
        "short_name": "Kesavananda Bharati",
        "court": "Supreme Court of India",
        "year": 1973,
        "reported_citation": "(1973) 4 SCC 225",
        "alt_citations": ["AIR 1973 SC 1461"],
        "case_number": "Writ Petition (Civil) No. 135 of 1970",
        "topics": ["constitutional law", "basic structure doctrine", "Article 368", "amendment power"],
        "holding": "The power of Parliament to amend the Constitution under Article 368 does not extend to altering the basic structure or framework of the Constitution. The 13 judges' bench overruled Golak Nath's restriction on amendment power while imposing the basic structure limitation.",
        "principles": [
            {"kind": "principle", "text": "Article 368 does not enable Parliament to alter the basic structure or essential features of the Constitution. The amendment power is wide but not unlimited; elements such as supremacy of the Constitution, republican and democratic form of government, secularism, separation of powers and federalism form part of the basic structure which cannot be abrogated even by constitutional amendment."},
            {"kind": "principle", "text": "A constitutional amendment under Article 368 is 'law' within the meaning of Article 13, and to the extent it violates fundamental rights or the basic structure it can be struck down by courts. Judicial review itself is an integral feature of the Constitution."},
        ],
    },
    {
        "slug": "maneka-gandhi-v-union-of-india-1978",
        "case_name": "Maneka Gandhi v. Union of India",
        "short_name": "Maneka Gandhi",
        "court": "Supreme Court of India",
        "year": 1978,
        "reported_citation": "(1978) 1 SCC 248",
        "alt_citations": ["AIR 1978 SC 597"],
        "case_number": "Writ Petition (Civil) No. 231 of 1977",
        "topics": ["Article 21", "natural justice", "personal liberty", "procedure established by law", "passport"],
        "holding": "The procedure contemplated by Article 21 for depriving a person of life or personal liberty must be right, just and fair, not arbitrary, fanciful or oppressive. Articles 14, 19 and 21 are not mutually exclusive but form a single scheme. Natural justice is a necessary ingredient of fair procedure.",
        "principles": [
            {"kind": "principle", "text": "Any procedure established by law for depriving personal liberty under Article 21 must satisfy the requirements of reasonableness, fairness and non-arbitrariness under Articles 14 and 19. The golden triangle of Articles 14, 19 and 21 protects life and personal liberty together."},
            {"kind": "principle", "text": "The principle of audi alteram partem is attracted where an authority makes an order adversely affecting a person, unless expressly excluded. Fairness in state action is an essential requirement of due process as understood in India after this judgment."},
        ],
    },
    {
        "slug": "hussainara-khatoon-i-v-state-of-bihar-1980",
        "case_name": "Hussainara Khatoon (I) v. Home Secretary, State of Bihar",
        "short_name": "Hussainara Khatoon",
        "court": "Supreme Court of India",
        "year": 1980,
        "reported_citation": "(1980) 1 SCC 81",
        "alt_citations": ["AIR 1980 SC 1819"],
        "topics": ["speedy trial", "undertrial prisoners", "Article 21", "legal aid", "free legal services"],
        "holding": "A speedy trial is an integral and essential part of the fundamental right to life and liberty under Article 21. Undertrials languishing in jail for periods exceeding the maximum sentence were ordered released; the State was directed to provide free legal aid to indigent accused.",
        "principles": [
            {"kind": "principle", "text": "Speedy trial is of the essence of criminal justice and is part of the fundamental right to life and liberty guaranteed under Article 21. Where the trial is delayed beyond reasonable limits, the court can order release of undertrial prisoners on bail or otherwise."},
            {"kind": "principle", "text": "Free legal services to an accused who is unable to secure legal representation is a State obligation flowing from Articles 21 and 39A, and a trial conducted without offering such aid where required would be vitiated."},
        ],
    },
    {
        "slug": "minerva-mills-v-union-of-india-1980",
        "case_name": "Minerva Mills Ltd. v. Union of India",
        "short_name": "Minerva Mills",
        "court": "Supreme Court of India",
        "year": 1980,
        "reported_citation": "(1980) 3 SCC 625",
        "alt_citations": ["AIR 1980 SC 1789"],
        "topics": ["basic structure", "Article 368", "judicial review", "Articles 14 and 19 balance"],
        "holding": "Sections 4 and 55 of the 42nd Amendment, which removed all limitations on amending power and judicial review of amendments, were struck down. Limited amending power and judicial review as its corollary are themselves basic features of the Constitution. Destroying the balance between Parts III and IV destroys the Constitution's basic structure.",
        "principles": [
            {"kind": "principle", "text": "Parliament's limited power of amendment and the Supreme Court's power of judicial review form part of the basic structure. Clause (4) and (5) inserted in Article 368 conferring unlimited amending power were held unconstitutional."},
            {"kind": "principle", "text": "Harmony between fundamental rights and directive principles is a basic feature; absolute primacy of either would destroy the balance envisaged by the Constitution. A total emasculation of fundamental rights would equally violate the basic structure."},
        ],
    },
    {
        "slug": "olga-tellis-v-bombay-municipal-corporation-1985",
        "case_name": "Olga Tellis v. Bombay Municipal Corporation",
        "short_name": "Olga Tellis",
        "court": "Supreme Court of India",
        "year": 1985,
        "reported_citation": "(1985) 3 SCC 545",
        "alt_citations": ["AIR 1986 SC 180"],
        "topics": ["right to livelihood", "Article 21", "eviction", "pavement dwellers", "due process"],
        "holding": "The right to livelihood flows from the right to life under Article 21. Eviction of pavement and slum dwellers without notice and hearing is unconstitutional; procedural fairness including prior notice is required before deprivation of livelihood, though no person has a right to encroach on public footpaths.",
        "principles": [
            {"kind": "principle", "text": "The right to life under Article 21 includes the right to livelihood, since no person can live without the means of living. Deprivation of livelihood without a fair procedure would amount to deprivation of life."},
            {"kind": "principle", "text": "Before evicting pavement dwellers or slum residents, the authorities must follow a just and fair procedure: issuance of notice and opportunity to be heard are imperative, and section 314 of the Bombay Municipal Corporation Act must be read down accordingly."},
        ],
    },
    {
        "slug": "bandhua-mukti-morcha-v-union-of-india-1984",
        "case_name": "Bandhua Mukti Morcha v. Union of India",
        "short_name": "Bandhua Mukti Morcha",
        "court": "Supreme Court of India",
        "year": 1984,
        "reported_citation": "(1984) 3 SCC 161",
        "alt_citations": ["AIR 1984 SC 802"],
        "topics": ["bonded labour", "Article 21", "Article 23", "public interest litigation", "epistolary jurisdiction"],
        "holding": "A letter addressed to a judge alleging bonded labour can be treated as a writ petition under Article 32. The right to live with human dignity under Article 21 derives its life breath from the Directive Principles, and the State is bound to ensure identification, release and rehabilitation of bonded labourers.",
        "principles": [
            {"kind": "principle", "text": "It is the sacred duty of the State to identify, release and rehabilitate bonded labourers, and the right to live with human dignity enshrined in Article 21 derives its content from the Directive Principles of State Policy including Clauses (e) and (f) of Article 39."},
            {"kind": "principle", "text": "Where the poor and disadvantaged sections of society cannot approach the court, a letter or telegram addressed to the Court may be entertained as a petition under Article 32; procedural technicalities yield to the cause of justice in public interest litigation."},
        ],
    },
    {
        "slug": "dk-basu-v-state-of-west-bengal-1997",
        "case_name": "D.K. Basu v. State of West Bengal",
        "short_name": "D.K. Basu",
        "court": "Supreme Court of India",
        "year": 1997,
        "reported_citation": "(1997) 1 SCC 416",
        "alt_citations": ["AIR 1997 SC 610"],
        "topics": ["arrest", "custodial violence", "Article 21", "guidelines", "custodial death compensation"],
        "holding": "Custodial torture and death violate Article 21; monetary compensation is an available remedy for infringement of fundamental rights. Eleven mandatory requirements were laid down for arrest and detention, including preparation of a memo of arrest attested by a witness and informing a relative or friend.",
        "principles": [
            {"kind": "principle", "text": "Any form of torture or cruel, inhuman or degrading treatment during arrest, detention or interrogation falls foul of Article 21, whether it occurs during investigation, interrogation or otherwise, and the State remains liable for such violation by its agents."},
            {"kind": "principle", "text": "Award of monetary compensation for established infringement of the indefeasible right to life under Article 21 is a remedy available in public law, distinct from private law damages, premised on strict liability of the State."},
            {"kind": "principle", "text": "Requirements for arrest and detention include preparation of a memo of arrest at the time of arrest attested by at least one witness, information regarding arrest and place of custody being communicated to a relative or friend, and entries in the custody register."},
        ],
    },
    {
        "slug": "vishaka-v-state-of-rajasthan-1997",
        "case_name": "Vishaka v. State of Rajasthan",
        "short_name": "Vishaka",
        "court": "Supreme Court of India",
        "year": 1997,
        "reported_citation": "(1997) 6 SCC 241",
        "alt_citations": ["AIR 1997 SC 3011"],
        "topics": ["sexual harassment", "workplace", "Article 15", "international conventions", "guidelines legislation"],
        "holding": "Sexual harassment at the workplace violates Articles 14, 15 and 21. In the absence of domestic legislation, guidelines laid down in international conventions such as CEDAW could be read into fundamental rights, and binding directions were issued defining sexual harassment and mandating complaint mechanisms.",
        "principles": [
            {"kind": "principle", "text": "Each incident of sexual harassment of a working woman at her workplace results in violation of her fundamental rights to gender equality and to life and liberty, and it is the duty of the employer to prevent such acts and provide mechanisms for redressal."},
            {"kind": "principle", "text": "In the absence of enacted law, international conventions and norms relevant for the guarantee of gender equality may be read into fundamental rights, and the Court may frame binding guidelines to fill the legislative vacuum until suitable legislation is enacted."},
        ],
    },
    {
        "slug": "l-chandra-kumar-v-union-of-india-1997",
        "case_name": "L. Chandra Kumar v. Union of India",
        "short_name": "L. Chandra Kumar",
        "court": "Supreme Court of India",
        "year": 1997,
        "reported_citation": "(1997) 9 SCC 406",
        "alt_citations": ["AIR 1997 SC 1125"],
        "topics": ["judicial review", "tribunals", "Article 323A", "Article 323B", "alternative remedy", "basic structure"],
        "holding": "Judicial review under Articles 226/227 and 32 is part of the basic structure and cannot be excluded. Decisions of administrative tribunals created under Articles 323A/323B remain subject to scrutiny by the High Courts under Articles 226/227 and by the Supreme Court under Article 136.",
        "principles": [
            {"kind": "principle", "text": "Judicial review conferred by Articles 226, 227 and 32 upon the High Courts and the Supreme Court constitutes part of the basic structure of the Constitution, and exclusion of such review by statute or constitutional amendment is impermissible."},
            {"kind": "principle", "text": "Tribunals adjudicating service matters and other disputes do not displace the supervisory jurisdiction of the High Courts; their decisions remain subject to challenge before the Division Bench of the High Court under Articles 226 and 227, preserving an effective avenue of review."},
        ],
    },
    {
        "slug": "whirlpool-corporation-v-registrar-of-trade-marks-1998",
        "case_name": "Whirlpool Corporation v. Registrar of Trade Marks, Mumbai",
        "short_name": "Whirlpool Corporation",
        "court": "Supreme Court of India",
        "year": 1998,
        "reported_citation": "(1998) 8 SCC 1",
        "alt_citations": ["AIR 1998 SC 2621"],
        "topics": ["writ jurisdiction", "alternative remedy", "Article 226", "maintainability", "fundamental rights", "natural justice"],
        "holding": "The existence of an alternative statutory remedy does not bar the High Court's writ jurisdiction under Article 226 where the petition involves enforcement of fundamental rights, violation of natural justice, or actions taken without jurisdiction. Discretion to entertain remains with the High Court notwithstanding availability of alternate relief.",
        "principles": [
            {"kind": "principle", "text": "The rule of alternative remedy is a rule of discretion and not a rule of jurisdiction; it does not oust the power of the High Court under Article 226 where the order complained of is without jurisdiction, violates natural justice, or involves enforcement of fundamental rights."},
            {"kind": "principle", "text": "When an authority acts wholly without jurisdiction or in violation of principles of natural justice, the availability of an alternative statutory remedy does not operate as a bar to maintainability of the writ petition under Article 226."},
        ],
    },
    {
        "slug": "ks-puttaswamy-v-union-of-india-2017",
        "case_name": "Justice K.S. Puttaswamy (Retd.) v. Union of India",
        "short_name": "Puttaswamy (Privacy)",
        "court": "Supreme Court of India",
        "year": 2017,
        "reported_citation": "(2017) 10 SCC 1",
        "neutral_citation": "2017 INSC 822",
        "topics": ["privacy", "Article 21", "proportionality", "informational privacy", "dignity"],
        "holding": "A nine-judge bench unanimously held that the right to privacy is protected as an intrinsic part of the right to life and personal liberty under Article 21 and Part III. Privacy invasions require a law, a legitimate state aim, and proportionality between means and ends.",
        "principles": [
            {"kind": "principle", "text": "Privacy is a constitutionally protected fundamental right intrinsic to life and personal liberty under Article 21, comprising informational privacy, decisional autonomy and bodily integrity, and it travels across the spectrum of activities protected in Part III."},
            {"kind": "principle", "text": "An invasion of privacy must satisfy the test of proportionality: it must be sanctioned by law, pursue a legitimate aim, be proportionate to the object, and be accompanied by procedural safeguards against abuse."},
        ],
    },
    {
        "slug": "shayara-bano-v-union-of-india-2017",
        "case_name": "Shayara Bano v. Union of India",
        "short_name": "Shayara Bano",
        "court": "Supreme Court of India",
        "year": 2017,
        "reported_citation": "(2017) 9 SCC 1",
        "neutral_citation": "2017 INSC 817",
        "topics": ["triple talaq", "manifest arbitrariness", "Article 14", "essential religious practices"],
        "holding": "The practice of talaq-e-biddat (instant triple talaq) was held unconstitutional by a 3:2 majority as being manifestly arbitrary and violative of Article 14. The doctrine of manifest arbitrariness was developed as an independent ground for invalidating action under Article 14.",
        "principles": [
            {"kind": "principle", "text": "Manifest arbitrariness is a ground to invalidate legislation and state action under Article 14: something that is capricious, irrational or without adequate determining principle is manifestly arbitrary and hence unconstitutional."},
            {"kind": "principle", "text": "Whether a practice is an essential religious practice is to be determined with reference to the doctrines, texts and tenets of the religion concerned and not merely on assertions of religious leaders; practices found non-essential receive no protection under Article 25."},
        ],
    },
    {
        "slug": "navtej-singh-johar-v-union-of-india-2018",
        "case_name": "Navtej Singh Johar v. Union of India",
        "short_name": "Navtej Singh Johar",
        "court": "Supreme Court of India",
        "year": 2018,
        "reported_citation": "(2018) 10 SCC 1",
        "neutral_citation": "2018 INSC 790",
        "topics": ["Section 377", "decriminalization", "dignity", "privacy", "equality", "sexual orientation"],
        "holding": "Section 377 IPC insofar as it criminalized consensual sexual conduct between adults of the same sex was held unconstitutional as violative of Articles 14, 15, 19 and 21. Constitutional morality prevails over social morality; sexual orientation is an innate attribute protected by dignity and privacy.",
        "principles": [
            {"kind": "principle", "text": "Constitutional morality requires that the rights of even a minority, however unpopular or distrusted, be respected; popular conceptions of morality cannot override the guarantees of equality, dignity and privacy under the Constitution."},
            {"kind": "principle", "text": "Sexual orientation is natural and immutable, and discrimination on that ground violates Articles 14 and 15; criminalizing consensual adult same-sex conduct chills the exercise of fundamental freedoms under Article 19(1)(a) and (d)."},
        ],
    },
    {
        "slug": "common-cause-v-union-of-india-2018",
        "case_name": "Common Cause v. Union of India",
        "short_name": "Common Cause (Euthanasia)",
        "court": "Supreme Court of India",
        "year": 2018,
        "reported_citation": "(2018) 5 SCC 1",
        "neutral_citation": "2018 INSC 249",
        "topics": ["passive euthanasia", "living will", "Article 21", "dignity in death", "advance directives"],
        "holding": "The right to die with dignity is part of the right to life under Article 21. Passive euthanasia and advance directives (living wills) were recognized subject to procedural safeguards; the two-judge bench overruled Aruna Shanbaug's earlier position restricting such recognition to the legislature.",
        "principles": [
            {"kind": "principle", "text": "Dignity in the process of dying is as much a facet of Article 21 as dignity in living; a terminally ill patient undergoing unbearable suffering has the right to refuse life-prolonging medical treatment."},
            {"kind": "principle", "text": "Advance directives by competent adults refusing medical treatment in future terminal conditions are legally valid subject to strict procedural safeguards including certification by medical boards and judicial oversight."},
        ],
    },
    {
        "slug": "joseph-shine-v-union-of-india-2019",
        "case_name": "Joseph Shine v. Union of India",
        "short_name": "Joseph Shine",
        "court": "Supreme Court of India",
        "year": 2019,
        "reported_citation": "(2019) 3 SCC 39",
        "neutral_citation": "2019 INSC 149",
        "topics": ["adultery", "Section 497 IPC", "gender discrimination", "Article 14", "privacy", "marital autonomy"],
        "holding": "Section 497 IPC treating adultery as an offence was struck down as unconstitutional: it treated the wife as the husband's property, discriminated on the basis of gender stereotypes, and invaded privacy and dignity. Adultery remains a ground for civil consequences in matrimonial law.",
        "principles": [
            {"kind": "principle", "text": "Section 497 IPC's confinement of punishment to the male adulterer and immunity of the wife rested on the notion of the woman as property of the husband, denying her agency; such gender-based differentiation fails the twin test of intelligible differentia and rational nexus under Article 14."},
            {"kind": "principle", "text": "The criminal law cannot intrude into the private sphere of marriage to punish consensual adult conduct absent harm to others, since sexual privacy and marital autonomy fall within the protective ambit of Article 21 read with Puttaswamy."},
        ],
    },
    {
        "slug": "indian-young-lawyers-assn-v-state-of-kerala-2019",
        "case_name": "Indian Young Lawyers Association v. State of Kerala (Sabarimala)",
        "short_name": "Sabarimala",
        "court": "Supreme Court of India",
        "year": 2019,
        "reported_citation": "(2019) 11 SCC 1",
        "neutral_citation": "2019 INSC 990",
        "topics": ["religious freedom", "Article 25", "women entry", "essential religious practices", "constitutional morality"],
        "holding": "By 4:1 majority, the exclusion of women aged 10-50 from the Sabarimala temple was held unconstitutional as violative of Articles 14, 15, 19(1), 21, 25 and 26. Religious denomination rights under Article 26 cannot justify practices excluding women based solely on physiology.",
        "principles": [
            {"kind": "principle", "text": "Freedom of religion under Article 25 is available equally to women, and any practice excluding women from places of worship solely on the basis of their sex or physiology cannot claim protection under Articles 25 and 26."},
            {"kind": "principle", "text": "Individual dignity and equality override claims of religious custom where the custom stigmatizes persons on grounds of sex; constitutional morality mandates that courts weigh practices against fundamental rights rather than defer uncritically to tradition."},
        ],
    },
    {
        "slug": "anuradha-bhasin-v-union-of-india-2020",
        "case_name": "Anuradha Bhasin v. Union of India",
        "short_name": "Anuradha Bhasin",
        "court": "Supreme Court of India",
        "year": 2020,
        "reported_citation": "(2020) 3 SCC 637",
        "neutral_citation": "2020 INSC 53",
        "topics": ["internet shutdown", "freedom of speech", "Article 19", "proportionality", "indefinite suspension"],
        "holding": "Freedom of speech and expression via the internet is protected under Article 19(1)(a), and internet access is also integral to trade and commerce under Article 19(1)(g). Indefinite suspension orders are impermissible; orders must satisfy the proportionality test, be published, and be subject to judicial review.",
        "principles": [
            {"kind": "principle", "text": "Expression through the internet enjoys Article 19(1)(a) protection and indefinite suspension of internet services is impermissible; restrictions must be temporary, limited in extent, reviewed periodically, and justified by public emergency or public safety."},
            {"kind": "principle", "text": "Prohibitory measures affecting fundamental rights must pass the proportionality test laid down in Puttaswamy: legitimate goal, rational connection, necessity being the least restrictive measure, and a proper balance between the measure and its impact on rights."},
        ],
    },
    {
        "slug": "vijay-madanlal-choudhary-v-union-of-india-2022",
        "case_name": "Vijay Madanlal Choudhary v. Union of India",
        "short_name": "Vijay Madanlal Choudhary",
        "court": "Supreme Court of India",
        "year": 2022,
        "reported_citation": "2022 SCC OnLine SC 929",
        "neutral_citation": "2022 INSC 647",
        "topics": ["PMLA", "bail", "Section 45", "twin condition", "money laundering", "ECIR"],
        "holding": "All provisions of the Prevention of Money Laundering Act including Section 45 (twin conditions for bail), powers of arrest, search and seizure, attachment of property, and non-supply of ECIR were upheld as constitutional. The twin conditions were read to incorporate the spirit of Article 21 protections.",
        "principles": [
            {"kind": "principle", "text": "The twin conditions in Section 45 PMLA requiring the Public Prosecutor's opportunity to oppose bail and the court's satisfaction of reasonable grounds for innocence are constitutional, provided they are construed reasonably consistent with Article 21 jurisprudence."},
            {"kind": "principle", "text": "An ECIR is not analogous to an FIR and need not be supplied to the accused; however the accused retains the right to seek disclosure of relevant materials relied upon for prosecution and the court must apply its mind to such requests."},
        ],
    },
    {
        "slug": "romesh-thappar-v-state-of-madras-1950",
        "case_name": "Romesh Thappar v. State of Madras",
        "short_name": "Romesh Thappar",
        "court": "Supreme Court of India",
        "year": 1950,
        "reported_citation": "AIR 1950 SC 124",
        "alt_citations": ["1950 SCR 594"],
        "topics": ["freedom of press", "Article 19(1)(a)", "pre-censorship", "public safety"],
        "holding": "Pre-censorship of a journal under the Madras Maintenance of Public Order Act violated Article 19(1)(a); public safety and public order were held distinct, and the impugned provision was not saved by Article 19(2) as it then stood. Freedom of the press is foundational to democratic governance.",
        "principles": [
            {"kind": "principle", "text": "Freedom of speech and expression includes propagation and publication of ideas, and freedom of the press lies at the foundation of all democratic organizations; prior restraint of publication strikes at the very root of this freedom."},
            {"kind": "principle", "text": "Public order is distinct from public safety, and a law authorizing ban of publications for general maintenance of public order could not, as the law then stood, be justified under the enumerated exceptions in Article 19(2)."},
        ],
    },
    {
        "slug": "state-of-wb-v-anwar-ali-sarkar-1952",
        "case_name": "State of West Bengal v. Anwar Ali Sarkar",
        "short_name": "Anwar Ali Sarkar",
        "court": "Supreme Court of India",
        "year": 1952,
        "reported_citation": "AIR 1952 SC 75",
        "alt_citations": ["1952 SCR 284"],
        "topics": ["Article 14", "classification test", "special courts", "reasonable classification"],
        "holding": "A notification empowering the government to direct that certain cases be tried by special courts without any guiding policy was held violative of Article 14. Classification must rest on an intelligible differentia bearing a rational nexus to the object; selection of individuals or classes arbitrarily offends equality.",
        "principles": [
            {"kind": "principle", "text": "Article 14 forbids class legislation but permits reasonable classification founded on an intelligible differentia having a rational relation to the object sought to be achieved; absence of any determinate guiding principle renders selection arbitrary and void."},
            {"kind": "principle", "text": "Equality before the law prohibits differential treatment of persons similarly situated without a reasonable basis; discretionary selection of particular offences or offenders for special procedures without standards violates Article 14."},
        ],
    },
]

SEED_EDGES = [
    ("ks-puttaswamy-v-union-of-india-2017", "kesavananda-bharati-v-state-of-kerala-1973", "RELIES_ON", "Puttaswamy reaffirms the basic structure doctrine including judicial review as settled by Kesavananda Bharati."),
    ("ks-puttaswamy-v-union-of-india-2017", "maneka-gandhi-v-union-of-india-1978", "FOLLOWS", "Puttaswamy builds on Maneka Gandhi's reading of Articles 14, 19 and 21 as a unified guarantee of fair process."),
    ("navtej-singh-johar-v-union-of-india-2018", "ks-puttaswamy-v-union-of-india-2017", "APPLIES", "Navtej Johar applies Puttaswamy's privacy holding to strike down Section 377 as applied to consenting adults."),
    ("joseph-shine-v-union-of-india-2019", "ks-puttaswamy-v-union-of-india-2017", "APPLIES", "Joseph Shine relies on Puttaswamy to hold that criminalizing adultery invades marital privacy."),
    ("anuradha-bhasin-v-union-of-india-2020", "ks-puttaswamy-v-union-of-india-2017", "ADOPTS_TEST", "Anuradha Bhasin adopts the proportionality standard articulated in Puttaswamy for internet shutdown orders."),
    ("shayara-bano-v-union-of-india-2017", "kesavananda-bharati-v-state-of-kerala-1973", "REFERS_TO", "Shayara Bano considers whether talaq-e-biddat could be tested against the basic structure, referencing Kesavananda."),
    ("shayara-bano-v-union-of-india-2017", "state-of-wb-v-anwar-ali-sarkar-1952", "DEVELOPS", "Shayara Bano develops the Article 14 classification analysis of Anwar Ali Sarkar into the doctrine of manifest arbitrariness."),
    ("l-chandra-kumar-v-union-of-india-1997", "kesavananda-bharati-v-state-of-kerala-1973", "RELIES_ON", "L. Chandra Kumar holds judicial review to be part of the basic structure following Kesavananda Bharati."),
    ("l-chandra-kumar-v-union-of-india-1997", "minerva-mills-v-union-of-india-1980", "REFERS_TO", "L. Chandra Kumar refers to Minerva Mills on limits of amending power in striking clauses of Articles 323A/323B."),
    ("whirlpool-corporation-v-registrar-of-trade-marks-1998", "maneka-gandhi-v-union-of-india-1978", "CONSISTENT_WITH", "Whirlpool's recognition that fundamental-rights violations remove the alternative-remedy bar aligns with Maneka Gandhi's fair-process reading of Article 21."),
]

SEED_STATUTES = [
    {"act": "Constitution of India", "section": "Article 14", "title": "Equality before law", "body": "The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India."},
    {"act": "Constitution of India", "section": "Article 19(1)(a)", "title": "Freedom of speech and expression", "body": "All citizens shall have the right to freedom of speech and expression, subject to reasonable restrictions under Article 19(2) relating to sovereignty and integrity of India, security of the State, friendly relations with foreign States, public order, decency or morality, contempt of court, defamation or incitement to an offence."},
    {"act": "Constitution of India", "section": "Article 21", "title": "Protection of life and personal liberty", "body": "No person shall be deprived of his life or personal liberty except according to procedure established by law."},
    {"act": "Constitution of India", "section": "Article 32", "title": "Remedies for enforcement of fundamental rights", "body": "The right to move the Supreme Court by appropriate proceedings for the enforcement of the rights conferred by Part III is guaranteed, and the Supreme Court shall have power to issue directions or orders or writs including writs in the nature of habeas corpus, mandamus, prohibition, quo warranto and certiorari."},
    {"act": "Constitution of India", "section": "Article 226", "title": "Power of High Courts to issue certain writs", "body": "Notwithstanding anything in Article 32 every High Court shall have power, throughout the territories in relation to which it exercises jurisdiction, to issue to any person or authority, including in appropriate cases any Government, within those territories directions, orders or writs, including writs in the nature of habeas corpus, mandamus, prohibition, quo warranto and certiorari, or any of them, for the enforcement of any of the rights conferred by Part III and for any other purpose."},
    {"act": "Constitution of India", "section": "Article 39A", "title": "Equal justice and free legal aid", "body": "The State shall secure that the operation of the legal system promotes justice, on a basis of equal opportunity, and shall provide free legal aid to ensure that opportunities for securing justice are not denied to any citizen by reason of economic or other disabilities."},
    {"act": "Registration Act, 1908", "section": "Section 17", "title": "Documents of which registration is compulsory", "body": "Non-testamentary instruments purporting or operating to create, declare, assign, limit or extinguish, whether present or future, any right, title or interest in immovable property of the value of one hundred rupees and upwards are required to be registered."},
    {"act": "Registration Act, 1908", "section": "Section 49", "title": "Effect of non-registration", "body": "Documents required by Section 17 to be registered shall not affect any immovable property comprised therein, or confer any power to adopt, or be received as evidence of any transaction affecting such property, unless registered, save as provided by specific exceptions."},
]


def seed(db):
    slug_to_id = {}
    for c in SEED_CASES:
        case_id = db.upsert_case(c)
        slug_to_id[c["slug"]] = case_id
        if not db.paragraphs_for_case(case_id):
            db.add_judgment_with_paragraphs(case_id, c["principles"])
    for src, tgt, rel, ev in SEED_EDGES:
        s = slug_to_id.get(src)
        t = slug_to_id.get(tgt)
        if s and t:
            db.add_edge(s, t, rel, ev)
    existing_statutes = {f"{r['act']}|{r['section']}" for r in db.all_statutes()}
    for s in SEED_STATUTES:
        key = f"{s['act']}|{s['section']}"
        if key not in existing_statutes:
            db.add_statute(s)
